### ISSUE TITLE
Native library loading incompatible with Tomcat classloader

### ISSUE THREAD

**Issue by zerodivide1** [scream3r/java-simple-serial-connector#69]
When a webapp is loaded in Tomcat that also loads JSSC, then the webapp is restarted, the JNI library is unable to load, resulting in the following error message:

```
java.lang.UnsatisfiedLinkError: Native Library /Users/spayne/.jssc/mac_os_x/libjSSC-2.8_x86_64.jnilib already loaded in another classloader
```

This is likely caused by the following line:
https://github.com/scream3r/java-simple-serial-connector/blob/2.8.0/src/java/jssc/SerialNativeInterface.java#L172

**Comment by tobiascapin** [comment]
Try to copy the jssc library into the tomcat lib folder.
I'm currently using jssc in a webapp in a tomcat server.

**Comment by dmak** [comment]
@zerodivide1: This is known problem in JVM. Native library is loaded only once and when the attempt is made to load it again, the exception like above occurs. The solution is either to make a library a system (like @tobiascapin suggests), then it will be associated with application server classloader. Or to save library each time under new random path (`/tmp/abc1/libjssc.jnilib`, `/tmp/abc2/libjssc.jnilib`, ...). In this case there is a chance that if JVM crashes the library is not removed, e.g. will trash tmp directory.
In principle the problematic class loader should be garbage collected (and release the library), but on some reason that does not happen.
