### ISSUE TITLE
RaspberryPi: UnsatisfiedLinkError: libjSSC-2.7_armhf.so: file too short

### ISSUE THREAD

**Issue by platisd** [scream3r/java-simple-serial-connector#93]
Hi,
I am trying to run code that uses your library (i.e. the examples) on a Raspberry Pi, however I keep getting the same error. Note that the code works perfectly fine on an Ubuntu 14.04 laptop.

Both machines run the latest Java 8 version:
Raspberry Pi java version "1.8.0_91"
Ubuntu 14.04 java version "1.8.0_92"

The error that I get, either when trying to run a jar OR with javac and the appropriate flags:

> Java HotSpot(TM) Client VM warning: You have loaded library /home/pi/.jssc/linux/libjSSC-2.7_armhf.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
> Caused by: java.lang.UnsatisfiedLinkError: /home/pi/.jssc/linux/libjSSC-2.7_armhf.so: /home/pi/.jssc/linux/libjSSC-2.7_armhf.so: file too short
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:172)
> 	at jssc.SerialPort.<init>(SerialPort.java:118)
> 	at serial.SerialHandler.initSerial(SerialHandler.java:29)
> 	at serial.SerialHandler.<init>(SerialHandler.java:21)
> 	at bridge.BridgeMain.main(BridgeMain.java:9)

Will be grateful for any hints! Thanks

**Comment by platisd** [comment]
Oh nevermind, after banging my head on the wall for one day, I just found out why this was happening. Apparently, the file /home/pi/.jssc/linux/libjSSC-2.7_armhf.so was **literally** too short, i.e. 0 bytes. I replaced it with [this one](https://github.com/scream3r/java-simple-serial-connector/blob/63a7fb64070daa0780be23df37bd007bb1eba3e6/src/java/libs/linux/libjSSC-2.7_armhf.so) that I got from your repo and everything works as it should.

Thanks for your work btw. :+1:

**Comment by davidbro-in** [comment]
@scream3r I think this *issue* should be reopened. We have had this situation too often.
